general:
  focus_follows_cursor: false
  toggle_workspace_on_refocus: false
  cursor_jump:
    enabled: true
    trigger: 'monitor_focus'

gaps:
  inner_gap: '10px'
  outer_gap:
    top: '10px'
    right: '10px'
    bottom: '10px'
    left: '10px'

window_effects:
  focused_window:
    border:
      enabled: true
      color: '#414868'
  other_windows:
    border:
      enabled: true
      color: '#24283b'

window_behavior:
  initial_state: 'tiling'
  state_defaults:
    floating:
      centered: false
      shown_on_top: true
    fullscreen:
      maximized: true
      shown_on_top: true

workspaces:
  - name: '1'
    bind_to_monitor: 1
    keep_alive: true
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'

window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture-in-[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys.PowerAccent' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper*' }

  - commands: ['set-floating']
    match:
      - window_title: { regex: '[Cc]alculatrice' }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['left']
      - commands: ['resize --width +2%']
        bindings: ['right']
      - commands: ['resize --height +2%']
        bindings: ['up']
      - commands: ['resize --height -2%']
        bindings: ['down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

  # When enabled, all keybindings are disabled except for lalt+shift+p which
  # returns to default keybindings.
  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['lalt+shift+p']

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['lalt+left']
  - commands: ['focus --direction right']
    bindings: ['lalt+right']
  - commands: ['focus --direction up']
    bindings: ['lalt+up']
  - commands: ['focus --direction down']
    bindings: ['lalt+down']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['lalt+shift+left']
  - commands: ['move --direction right']
    bindings: ['lalt+shift+right']
  - commands: ['move --direction up']
    bindings: ['lalt+shift+up']
  - commands: ['move --direction down']
    bindings: ['lalt+shift+down']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['lalt+r']

  # Disables all keybindings until lalt+shift+p is pressed again.
  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['lalt+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['lalt+v']

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['lalt+shift+space']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['lalt+f']

  # Close focused window.
  - commands: ['close']
    bindings: ['lalt+shift+q']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['lalt+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['lalt+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['lalt+shift+w']

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ['shell-exec wt']
    bindings: ['lalt+enter']

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ['focus --prev-workspace']
    bindings: ['lalt+a']
  - commands: ['focus --next-workspace']
    bindings: ['lalt+d']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['lalt+1']
  - commands: ['focus --workspace 2']
    bindings: ['lalt+2']
  - commands: ['focus --workspace 3']
    bindings: ['lalt+3']
  - commands: ['focus --workspace 4']
    bindings: ['lalt+4']
  - commands: ['focus --workspace 5']
    bindings: ['lalt+5']
  - commands: ['focus --workspace 6']
    bindings: ['lalt+6']
  - commands: ['focus --workspace 7']
    bindings: ['lalt+7']
  - commands: ['focus --workspace 8']
    bindings: ['lalt+8']
  - commands: ['focus --workspace 9']
    bindings: ['lalt+9']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['lalt+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['lalt+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['lalt+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['lalt+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['lalt+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['lalt+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['lalt+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['lalt+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['lalt+shift+9']

